import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossOrigin="anonymous"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
          integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
          crossOrigin="anonymous"
        ></Script>
        <script src="https://dubai.dubizzle.com/We-a-did-and-He-him-as-desir-call-their-Banquo-B"></script>
        <meta name="viewport" content="width=device-width" />
        <link rel="preconnect" href="https://tags.crwdcntrl.net" />
        <link rel="preconnect" href="https://bcp.crwdcntrl.net" />
        <link rel="preconnect" href="https://c.ltmsphrcl.net" />
        <link rel="dns-prefetch" href="https://tags.crwdcntrl.net" />
        <link rel="dns-prefetch" href="https://bcp.crwdcntrl.net" />
        <link rel="dns-prefetch" href="https://c.ltmsphrcl.net" />
        <title>
          AED22,030/month | 2024 Ferrari 296 GTS 2.9L | GCC Specifications |
          Ref#255664 | dubizzle{" "}
        </title>
        <link
          rel="canonical"
          href="https://dubai.dubizzle.com/motors/used-cars/ferrari/296-gts/2024/11/13/aed22030month-2024-ferrari-296-gts-29l-gcc-2-106---27b548cf1440483197dfcc0d58f11aa8/"
        />
        <link
          rel="alternate"
          hrefLang="en"
          href="https://dubai.dubizzle.com/motors/used-cars/ferrari/296-gts/2024/11/13/aed22030month-2024-ferrari-296-gts-29l-gcc-2-106---27b548cf1440483197dfcc0d58f11aa8/"
        />
        <link
          rel="alternate"
          hrefLang="ar"
          href="https://dubai.dubizzle.com/ar/motors/used-cars/ferrari/296-gts/2024/11/13/aed22030month-2024-ferrari-296-gts-29l-gcc-2-106---27b548cf1440483197dfcc0d58f11aa8/"
        />
        <meta name="robots" content="index, follow"></meta>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <link rel="preconnect" href="https://tags.crwdcntrl.net" />
        <link rel="preconnect" href="https://bcp.crwdcntrl.net" />
        <link rel="preconnect" href="https://c.ltmsphrcl.net" />
        <link rel="dns-prefetch" href="https://tags.crwdcntrl.net" />
        <link rel="dns-prefetch" href="https://bcp.crwdcntrl.net" />
        <link rel="dns-prefetch" href="https://c.ltmsphrcl.net" />
        <meta property="og:title" content="Amazing Image Preview" />
        <meta
          property="og:description"
          content="Check out this amazing image!"
        />
        <meta
          property="og:image"
          content="https://fastly.picsum.photos/id/0/800/600.jpg?hmac=qRIxZPb6D3nnquI4AQ4xTVwhTvVx1FL3Pdm29Jz61fQ"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
